### ISSUE TITLE
Quadratic Program Formulation

### ISSUE THREAD

**Issue by shoshievass** [YimingYAN/cppipm#7]
To be totally sure I'm using this correctly - could you please clarify how the (Q,A,b,c) formulation relates to the [standard](https://www.mathworks.com/discovery/quadratic-programming.html) (H,f,Aeq,beq,Aineq,bineq) one?

```
min_x  1/2 H' x H + f' x
s.t.
A_eq x = b_eq
A_in x \leq b_ineq
```

**Comment by YimingYAN** [comment]
I think the formulation i used internally in the solver is:

```
min_x  1/2 Q' x Q + c' x
s.t.
A x = b
x >= 0
```

So for your case, you have to convert your formulation to the above by adding slack to the inequality constraints.

Is your x always negative? namely, ``` x>=0```?

**Comment by shoshievass** [comment]
My `x` is always positive so that `x>=0` would be fine. 

The reason I'm confused is that in the mpsreader, it looks like you instantiate the Q and A matrices with `n_rows_inq` in both - maybe that's a misreading?

```
void mpsReader::_initializeData()
{
    Q   = mat::Zero(n_cols + n_rows_inq   , n_cols + n_rows_inq);
    A   = mat::Zero(n_rows_inq + n_rows_eq, n_cols + n_rows_inq);
    b   = vec::Zero(n_rows_inq + n_rows_eq);
    c   = vec::Zero(n_cols + n_rows_inq   );
    lb  = vec::Zero(n_cols + n_rows_inq   );
    ub  = vec(n_cols+n_rows_inq);  ub.fill(infty);
    
    objsense = "MIN";
}
```

**Comment by YimingYAN** [comment]
Ah, OK. The MpsReader converts the MPS format to the format required by the solver.  
```
A_eq x = b_eq
A_inq x <= b_inq
```
will be converted to 
```
A_eq x = b_eq
A_inq x + s = b_inq
```

The  the matrix ```"A"``` becomes 
```     
       [  A_eq     ZeroMatrix     ]
A = [   A_inq   IdentityMatrix]

```
and this is why the dimension for ```A``` is ```(n_rows_inq + n_rows_eq) x (n_cols + n_rows_inq)```

**Comment by shoshievass** [comment]
Got it. So I should instantiate `A` and `b` with `I` and `zeros` at the end? What about the `n_rows_inq` in `Q`?

**Comment by shoshievass** [comment]
Got it. I'm sorry to drag on about this - I'm trying to get a toy example to work and can't seem to get it..

The problem is:
Q = (0.45, 0 ; 0, 1.8)
c = (-5.175, -26.4)
A_eq = (1, 1; 0,0)
b_eq = (82.5, 0)
A_ineq = (1, 0; 0, 1)
b_ineq = (0,0)

[Prettier version w/ unnecessary info here](https://github.com/YimingYAN/cppipm/files/1928729/toyexample.pdf)

I'm trying the following, given your points above:

```
cout << "\nTest Toy Example Problem: "<<endl;
    int n_cols = 2;
    int n_rows_inq = 2;
    int n_rows_eq = 2;

    mat Q   = mat::Zero(n_cols + n_rows_inq  , n_cols + n_rows_inq);
    mat A   = mat::Zero(n_rows_eq + n_rows_inq, n_rows_inq + n_rows_inq);
    vec b   = vec::Zero(n_rows_eq + n_rows_inq);
    vec c   = vec::Zero(n_cols );
	
	Q(1,1) = 0.45;
	Q(2,2) = 1.8;
	
	A(1,1) = 1;
	A(1,2) = 1;
	A(3,3) = 1;
	A(4,4) = 1;
	b(1,1) = 82.5;
	c(1) = -5.175;
	c(2) = -26.4;

    // qp test
    cout<<"\nQP problem:"<<endl;
    Algorithm* qp_test = new cppipm(Q, A, b, c);
    qp_test->solve();
```

And I'm getting the error:
`Assertion failed: (row >= 0 && row < rows() && col >= 0 && col < cols()), function operator(), file ../lib/Eigen/src/Core/DenseCoeffsBase.h, line 350.`

Apologies in advance if my error is a silly beginner mistake - I appreciate the help in getting this working!

**Comment by YimingYAN** [comment]
In summary, your formulation should be converted to 

```
min_(x,s) 1/2 [H' ZeroMatrix] (x,s) [H ZeroMatrix] + [f' ZeroVector] (x,s)
s.t.
    [  A_eq     ZeroMatrix     ] [x] = [b_eq]
    [  A_inq    IdentityMatrix ] [s]     [b_inq]
 (x,s) >=0


```

**Comment by YimingYAN** [comment]
A_ineq = (1, 0; 0, 1)
b_ineq = (0,0)

first of all, this is wrong:
A_ineq = (-1, 0; 0, -1)
b_ineq = (0,0)
the direction is ```>=```

It seems the dimensions of the matrices are not correct

**Comment by YimingYAN** [comment]
A(1,1) = 1;
	A(1,2) = 1;
	A(3,3) = 1;
	A(4,4) = 1;
Mising A_ineq
A(3,1) = -1
A(4,2) = -1

**Comment by YimingYAN** [comment]
most crucial part:

vec c   = vec::Zero(n_cols );

should be 

vec c   = vec::Zero(n_cols + n_ineq );

**Comment by shoshievass** [comment]
Me too! 

I added in all these changes (and found another - I had a typo in the col dims of A) but it's still giving me the same error :/
```
   cout << "\nTest Toy Example Problem: "<<endl;
    int n_cols = 2;
	int n_rows_inq = 2;
	int n_rows_eq = 2;

    mat Q   = mat::Zero(n_cols + n_rows_inq  , n_cols + n_rows_inq);
    mat A   = mat::Zero(n_rows_eq + n_rows_inq, n_rows_eq + n_rows_inq);
    vec b   = vec::Zero(n_rows_eq + n_rows_inq);
    vec c   = vec::Zero(n_cols + n_rows_inq);
	
	Q(1,1) = 0.45;
	Q(2,2) = 1.8;
	
	A(1,1) = 1;
	A(1,2) = 1;
	A(3,1) = -1;
	A(4,2) = -1;
	A(3,3) = 1;
	A(4,4) = 1;
	b(1,1) = 82.5;
	c(1) = -5.175;
	c(2) = -26.4;

    // qp test
    cout<<"\nQP problem:"<<endl;
    Algorithm* qp_test = new cppipm(Q, A, b, c);
    qp_test->solve();
```

**Comment by YimingYAN** [comment]
Ah ha
This is c++, not matlab. index starts from 0 not 1.

**Comment by shoshievass** [comment]
ahhhh of course! :palm -> face:. Thank you.

Ok it runs now, but produces a nonsensical answer :X 
I'll try to see if there's something wrong with the indexing or the signs...

Test Toy Example Problem Try: 

QP problem:
 Iter  Residual        Mu    Alphax    Alphas
    0       nan       nan       ---       ---
    1       nan       nan  1.00e+00  1.00e+00
    2       nan       nan  1.00e+00  1.00e+00
    3       nan       nan  1.00e+00  1.00e+00
    4       nan       nan  1.00e+00  1.00e+00
    5       nan       nan  1.00e+00  1.00e+00
    6       nan       nan  1.00e+00  1.00e+00
    7       nan       nan  1.00e+00  1.00e+00
    8       nan       nan  1.00e+00  1.00e+00
    9       nan       nan  1.00e+00  1.00e+00
   10       nan       nan  1.00e+00  1.00e+00
   11       nan       nan  1.00e+00  1.00e+00
   12       nan       nan  1.00e+00  1.00e+00
   13       nan       nan  1.00e+00  1.00e+00
   14       nan       nan  1.00e+00  1.00e+00
   15       nan       nan  1.00e+00  1.00e+00
   16       nan       nan  1.00e+00  1.00e+00
   17       nan       nan  1.00e+00  1.00e+00
   18       nan       nan  1.00e+00  1.00e+00
   19       nan       nan  1.00e+00  1.00e+00
   20       nan       nan  1.00e+00  1.00e+00
   21       nan       nan  1.00e+00  1.00e+00
   22       nan       nan  1.00e+00  1.00e+00
   23       nan       nan  1.00e+00  1.00e+00
   24       nan       nan  1.00e+00  1.00e+00
   25       nan       nan  1.00e+00  1.00e+00
   26       nan       nan  1.00e+00  1.00e+00
   27       nan       nan  1.00e+00  1.00e+00
   28       nan       nan  1.00e+00  1.00e+00
   29       nan       nan  1.00e+00  1.00e+00
   30       nan       nan  1.00e+00  1.00e+00
   31       nan       nan  1.00e+00  1.00e+00
   32       nan       nan  1.00e+00  1.00e+00
   33       nan       nan  1.00e+00  1.00e+00
   34       nan       nan  1.00e+00  1.00e+00
   35       nan       nan  1.00e+00  1.00e+00
   36       nan       nan  1.00e+00  1.00e+00
   37       nan       nan  1.00e+00  1.00e+00
   38       nan       nan  1.00e+00  1.00e+00
   39       nan       nan  1.00e+00  1.00e+00
   40       nan       nan  1.00e+00  1.00e+00
   41       nan       nan  1.00e+00  1.00e+00
   42       nan       nan  1.00e+00  1.00e+00
   43       nan       nan  1.00e+00  1.00e+00
   44       nan       nan  1.00e+00  1.00e+00
   45       nan       nan  1.00e+00  1.00e+00
   46       nan       nan  1.00e+00  1.00e+00
   47       nan       nan  1.00e+00  1.00e+00
   48       nan       nan  1.00e+00  1.00e+00
   49       nan       nan  1.00e+00  1.00e+00
   50       nan       nan  1.00e+00  1.00e+00
   51       nan       nan  1.00e+00  1.00e+00
----------------------------
CPPIPM Terminated. Status : 1
[Iters: 51] [Time: 1.79e-02s]

**Comment by YimingYAN** [comment]
Basically what happened was: the solver encountered an numerical issue because your problem formulation has a redundant row. Look at your formulation again, you have 

```
A_eq = [1 1]
            [0 0] 
b_eq = [82.5]
             [0] 
```
Essentially, your second equality constraint is ```0 = 0 ``` which make it redundant. In a more technical term, your problem formulation is not full row rank. This solver assume full row rank (all interior point method solvers assume this). Since this is a very small implementation, it does not come with the function to auto detect/remove redundant rows.

**Comment by shoshievass** [comment]
Ah! Thank you, this looks like it works!

One last beginner question! The `solve' function is void - how would you recommend pulling the optimal solution?

**Comment by YimingYAN** [comment]
Hmm, I cannot believe i forgot to implement this...

A simple way: 
add a line in the printFooter to print out x.
Or create a public function that returns the value of x.
